version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: corex_postgres
    restart: always
    environment:
      POSTGRES_DB: corex_db
      POSTGRES_USER: corex_user
      POSTGRES_PASSWORD: corex_password
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: