# Generated by Django 6.1.1 on 2026-09-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='prefijo',
            field=models.CharField(default='rtl', help_text='Ej: eco para ecommerce, rtl para retail, pos para puntos de venta', max_length=10),
        ),
    ]
