# Generated by Django 6.1.1 on 2026-09-29 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_servicio_prefijo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='notas_internas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='tokens_usados',
            field=models.TextField(blank=True, help_text='Tokens de API o accesos registrados', null=True),
        ),
        migrations.AddField(
            model_name='membresia',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membresia',
            name='fecha_mora',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membresia',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clienteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contratacion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido (Baja temporal)'), ('historico', 'Histórico / Finalizado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.servicio'),
        ),
        migrations.AlterField(
            model_name='contratacion',
            name='url_sistema',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='prefijo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
    ]
